myName = input("What is your name? ")
myAge = input("How old are you? ")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)

userName = input("What is your name? ")
userFood = input("What is your favorite food? ")
userMusic = input("What is your favorite music? ")
userLocation = input("Where do you live? ")
print()
print("You are")
print(userName)
print("You're probably hungry for")
print(userFood)
print("and you're definitely getting your groove on to")
print(userMusic)
print("living in the amazing")
print(userLocation)
