print("Welcome to adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
name = input("What is your name?")
enemy = input("Who is you worst enemy's name?")
superpower = input("What's your superpower?")
live = input("Where do you live?")
favouriteFood = input("What is your favourite food?")
print()
print("Hello,", name, "! Your ", superpower, " makes you extra special and unique.", enemy, " trembles at your presence, you are a force to reckon with.", live, " is a very good place to live and eat ", favouriteFood, " ,enjoy living life mate.")
